language: python
python:
- '3.4'
- pypy
before_install: pip install -r requirements.txt
deploy:
  provider: s3
  access_key_id: AKIAJQNKNIS56HLWPF6A
  secret_access_key:
    secure: fTJQPxU7k0ChokHgyRPapqGTL4Isq4nyGtxtu/sMu8/JGN0J0KLuZtkH/iV9mKoICEqpyY5axkxJJmFA3WdjbHDzUkl2Eg9c5aDUWwtgt3pgSeUavMjxmspptahnoVSLZWRYbaAo8BzKBbjRnVsT3Ozh+5JNwFcFoLKsGZPLJrSYEU5AkrpQ/AOc1nBlfLd78Ul00TOWnp9U7MT9iw1ZU0ZBWSEBn5nh/tVv4kUgaru9ZSKlZjO69rlRI1rF/VWj2hzrqZxbym2MvQiaJPP56hfUSRu+zmpV8nW2pl1dDOMLUVha66WbTf4kJ88N5SMlJWpaa9TWe/YUhEuFzUPwtY7VjbjqmDTpd9tBC8KWrY4/G64YvPEXyToffnYUc7dSMqsGRp/T3FYzds35eCRx9eaXSeUqP1cwo8Rf1rT9e9GYeMjzJl642O15s9xAo86bgfSscXD8U+PYkucGk//KC6uJNH0GO7Yeot/XWrRyKcQJHOy6bKwewzj26cyuEfECpDzu9vK6ualSQPfKIgzwsbLT/5U3biM+geE924LamuM4GQROoU0ZvuUCkNsgrRaM4YS/SJnIdxWruCBAJ80SZELX4G/frn6LUHf0lhrkf2BsdCDGkwKAoTZOV7pM24kvT0vKesPoLucTk/msX55A2RVOHBUaA4RkuG/spbmtfRw=
  bucket: pawelplewinski-deploy
  upload-dir: worker
  acl: public_read
  on:
    repo: pawelplewinski/psoir-worker
script: nosetests
